#- Type: Training
  #Trainers:
    #- Name: Ben Sadeghipour
     # Email: ben@sadeghipour.net
     #Image: /assets/images/trainers/BenSadeghipour.png
      #Twitter: NahamSec
      #Biography: >-
          # Ben is the Head of Hacker Education at HackerOne by day, and a hacker and content creator by night. He has helped identify over 700 security vulnerabilities across hundreds of web and mobile applications for 
          # companies such as Verizon Media, Red Bull, Apple, Airbnb, Snapchat, The US Department of Defense, Lyft, and more. One of the world’s top ethical hackers, he has invested time back into the security community 
          # by creating a community of 1000+ active hackers and hosting international conferences dedicated to hacker education and collaboration. He has also held free workshops and trainings to teach others about security 
          # and web application hacking.
      #TrainerId: trainer001
      #-Name: Trainer Dos
      #Email: tainer.dos@owasp.org
      #Image: /assets/images/trainers/staff_harold.jpg
      #Twitter: Trainer_Dos
      #Biography: The second trainer of this course is a cybersecurity certified professional with more than 125 years of
      #  experience. He works in the field of cybersecurity, cybersecurity research,
      #  and threat intelligence.
      #TrainerId: trainer_dos
  #Title: Introduction to Web Application Hacking & Bug Bounty (3-day training course)
  #URL: https://www.eventbrite.com/e/global-appsec-us-2021-virtual-training-tickets-188589806187
  #SectionId: sku_IWAHBB
  #Description:
